export const USER_REGISTRATION_REQUEST = 'USER_REGISTRATION_REQUEST';
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
export const USER_REGISTRATION_FAIL = 'USER_REGISTRATION_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const USER_LOGOUT = 'USER_LOGOUT';

export const SET_USERS = 'SET_USERS';
export const ADD_USER = 'ADD_USER';
export const USER_FETCHED = 'USER_FETCHED';
export const USER_UPDATED = 'USER_UPDATED';
export const USER_DELETED = 'USER_DELETED';

export const SET_DOCUMENTS = 'SET_DOCUMENTS';
export const ADD_DOCUMENT = 'ADD_DOCUMENT';
export const DOCUMENT_FETCHED = 'DOCUMENT_FETCHED';
export const DOCUMENT_UPDATED = 'DOCUMENT_UPDATED';
export const DOCUMENT_DELETED = 'DOCUMENT_DELETED';
export const SET_USER_DOCUMENTS = 'SET_USER_DOCUMENTS';

export const SET_FOLDERS = 'SET_FOLDERS';
export const ADD_FOLDER = 'ADD_FOLDER';
export const FOLDER_FETCHED = 'FOLDER_FETCHED';
export const FOLDER_UPDATED = 'FOLDER_UPDATED';
export const FOLDER_DELETED = 'FOLDER_DELETED';

export const USER_SEARCH_RESULTS = 'USER_SEARCH_RESULTS';
export const DOCUMENT_SEARCH_RESULTS = 'DOCUMENT_SEARCH_RESULTS';

